name: Delete a release asset
description: |
  A composite action that deletes a previously created release asset.
  Requires the `contents: write` permission to work.

inputs:
  asset-id:
    required: true
    description: "The ID of the asset to delete"
  owner:
    required: false
    default: ""
    description: "The repository owner"
  repo:
    required: false
    default: ""
    description: "The repository"
  retries:
    required: false
    default: "0"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"

runs:
  using: "composite"
  steps:
    - name: Upload asset
      id: upload-asset
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          github.rest.repos.deleteReleaseAsset({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            asset_id: ${{ inputs.asset-id }},
          });

