name: Remove assignees from pull request
description: |
  A composite action for removing a assignees from a github pull request.
  This requires `pull-requests: write` permissions in order to work correctly.

inputs:
  assignees:
    required: true
    description: "A list of assignees to remove, separated by either newlines or commas."
  pull-number:
    required: false
    default: "0"
    description: "The pull request number to comment on"
  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.

runs:
  using: "composite"
  steps:
    - name: Remove assignees from pull request
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.removeAssignees({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            issue_number: ${{ inputs.pull-number }} || context.issue.number,
            assignees: `${{ inputs.assignees }}`.split(/[\n,]/).map(s => s.trim()).filter(s => s)
          });
