name: Update issue
description: |
  A composite action for updating an existing github issue.
  This action will update _all_ fields of the issue, and thus should be used
  sparingly. Consider using the `issues/add-*` or `issues/remove-*` series of
  steps to alter the issue in-place.
  This requires `issues: write` permissions in order to work correctly.

inputs:
  issue-number:
    required: false
    default: "0"
    description: |
      The issue number to comment on.
      If not specified, this will attempt to retrieve the issue number from the
      Github `context` variable.
  title:
    required: true
    description: "The title to use for the issue"
  body:
    required: false
    default: ""
    description: "The body text of the github issue"
  labels:
    required: false
    default: ""
    description: "A list of labels to add, separated by newlines."
  assignees:
    required: false
    default: ""
    description: "A list of assignees to add, separated by newlines."
  owner:
    required: false
    default: ""
    description: "The repository owner"
  repo:
    required: false
    default: ""
    description: "The repository"
  retries:
    required: false
    default: "3"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"
outputs:
  issue-number:
    value: ${{ steps.create.outputs.issue-number }}
    description: "The number of the created issue"
  issue-url:
    value: ${{ steps.create.outputs.issue-url }}
    description: "The HTTP URL of the newly created issue"

runs:
  using: "composite"
  steps:
    - name: Create issue
      id: create
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          const { data: issue } = await github.rest.issues.update({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            issue_number: ${{ inputs.issue-number }} || context.issue.number,
            labels: `${{ inputs.labels }}`.split(/[\n,]/).map(s => s.trim()).filter(s => s),
            assignees: `${{ inputs.assignees }}`.split(/[\n,]/).map(s => s.trim()).filter(s => s),
            title: `${{ inputs.title }}`,
            body: `${{ inputs.body }}`,
          })
          core.setOutput('issue-number', issue.number)
          core.setOutput('issue-url', issue.html_url)
