name: Delete comment
description: |
  A composite action for deleting comments.
  This requires `issues: write` permissions in order to work correctly.

inputs:
  comment-id:
    required: true
    description: "The comment to delete"
  owner:
    required: false
    default: ""
    description: "The repository owner"
  repo:
    required: false
    default: ""
    description: "The repository"
  retries:
    required: false
    default: "0"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"

runs:
  using: "composite"
  steps:
    - name: Lock Issue
      id: update
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          github.rest.issues.deleteComment({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            comment_id: ${{ inputs.comment-id }}
          });
