name: Check repository collaborator
description: |
  A composite action that checks if a user is a collaborator with this repository.
  Requires the `contents: write` permission to work.

inputs:
  username:
    required: true
    description: The handle for the GitHub user account.
  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.
outputs:
  is-collaborator:
    value: ${{ steps.check.outputs.is-collaborator }}
    description: A boolean indicating whether the user is a collaborator

runs:
  using: "composite"
  steps:
    - name: Check collaborator
      id: check
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          const result = await github.rest.repos.checkCollaborator({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            username: `${{ inputs.username }}`
          });
          core.setOutput('is-collaborator', result.status == 204)
