name: Merge pull request
description: |
  A composite action for merging a pull request.
  This requires `pull-requests: write` permissions in order to work correctly.

inputs:
  pull-number:
    required: false
    default: "0"
    description: "The pull request number to comment on"
  commit-title:
    required: false
    default: ""
    description: |
      The commit title to use.
      Defaults to the pull-request title if not specified.
  commit-message:
    required: false
    default: ""
    description: |
      The commit message to use.
      Defaults to the pull-request message if not specified.
  sha:
    required: false
    default: ""
    description: |
      SHA that pull request head must match to allow merge.
  merge_method:
    required: false
    default: ""
    description: |
      The merge method to use.
      Can be one of: `merge`, `squash`, `rebase`.

  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.

runs:
  using: "composite"
  steps:
    - name: Merge pull request
      id: close
      uses: actions/github-script@v7
      env:
        COMMIT_TITLE: ${{ inputs.commit-title }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          await github.rest.pulls.merge({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            pull_number: ${{ inputs.pull-number }} || context.issue.number,
            commit_title: process.env.COMMIT_TITLE || undefined,
            commit_message: process.env.COMMIT_MESSAGE || undefined,
            sha: `${{ inputs.sha }}` || undefined,
            merge_method: `${{ inputs.merge-method }}` || undefined,
          });
