name: Delete a release
description: |
  Deletes a previously created release
  Requires the `content: write` permission to work.

inputs:
  release-id:
    required: true
    description: "The ID of the release"
  owner:
    required: false
    default: ""
    description: "The repository owner"
  repo:
    required: false
    default: ""
    description: "The repository"
  retries:
    required: false
    default: "0"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"
outputs:
  release-id:
    value: ${{ steps.create-release.outputs.release-id }}
    description: The browser URL of the uploaded asset

runs:
  using: "composite"
  steps:
    - name: Upload asset
      id: create-release
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          github.rest.repos.deleteRelease({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            release_id: `${{ inputs.release-id }}`,
          });
