name: Delete a release
description: |
  Deletes a previously created release
  Requires the `content: write` permission to work.

inputs:
  release-id:
    required: true
    description: "The ID of the release"
  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.
outputs:
  release-id:
    value: ${{ steps.create-release.outputs.release-id }}
    description: The browser URL of the uploaded asset

runs:
  using: "composite"
  steps:
    - name: Upload asset
      id: create-release
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          await github.rest.repos.deleteRelease({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            release_id: `${{ inputs.release-id }}`,
          });
