name: Get tag
description: |
  A composite action for getting a tag.
  This requires `contents: read` permissions in order to work correctly.

inputs:
  tag-name:
    required: true
    description: The name of the git tag to get.
  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.
outputs:
  sha:
    value: ${{ steps.get-tag.outputs.sha }}
    description: The SHA of the tag
  ref:
    value: ${{ steps.get-tag.outputs.ref }}
    description: The ref to the tag

runs:
  using: "composite"
  steps:
    - name: Get Tag
      id: get-tag
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          const { data: tag } = await github.rest.git.getRef({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            ref: 'tags/${{ inputs.tag-name }}`
          });
          core.setOutput('sha', tag?.object?.sha)
          core.setOutput('ref', tag?.ref)
