name: Close pull request
description: |
  A composite action for closing a pull request.
  This requires `pulls: write` permissions in order to work correctly.

inputs:
  pull-number:
    required: false
    default: "0"
    description: "The pull request number to comment on"
  owner:
    required: false
    default: ""
    description: |
      The repository owner.
      If unspecified, this will default to the owner of the current repository.
  repo:
    required: false
    default: ""
    description: |
      The name of the repository.
      If unspecified, this will default to the current repository.
  github-token:
    required: false
    default: "${{ github.token }}"
    description: |
      The default token to use for this Git operation.
      If unspecified, this will default to `github.token`.
  retries:
    required: false
    default: "0"
    description: |
      The number of times to attempt to retry if this fails.
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: |
      A list of error-codes that are exempt from being retried.
outputs:
  pull-number:
    value: ${{ steps.close.outputs.pull-number }}
    description: "The pull request number that was closed"

runs:
  using: "composite"
  steps:
    - name: Close pull request
      id: close
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        github-token: ${{ inputs.github-token }}
        script: |
          const { data: pull } = await github.rest.pulls.update({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            pull_number: ${{ inputs.pull_number }} || context.issue.number,
            state: 'closed'
          });
          core.setOutput('pull-number', pull.number)
