name: Add assignees to Pull Request
description: |
  A composite action for adding assignees to github pull requests.
  This requires `pull-requests: write` permissions in order to work correctly.

inputs:
  labels:
    required: true
    description: "A list of labels to add, separated by newlines."
  pull-number:
    required: false
    default: "0"
    description: "The pull request number to update"
  owner:
    required: false
    default: ""
    description: "The repository owner"
  repo:
    required: false
    default: ""
    description: "The repository"
  retries:
    required: false
    default: "0"
    description: "The number of times to try retrying"
  retry-exempt-status-codes:
    required: false
    default: "400,401,403,404,422"
    description: "The retry exempt status codes"

runs:
  using: "composite"
  steps:
    - name: Add assignees to pull request
      uses: actions/github-script@v7
      with:
        retries: ${{ inputs.retries }}
        retry-exempt-status-codes: ${{ inputs.retry-exempt-status-codes }}
        script: |
          github.rest.issues.addAssignees({
            owner: `${{ inputs.owner }}` || context.repo.owner,
            repo: `${{ inputs.repo }}` || context.repo.repo,
            issue_number: ${{ inputs.pull-number }} || context.issue.number,
            assignees: `${{ inputs.assignees }}`.split(/[\n,]/).map(s => s.trim()).filter(s => s)
          });
