name: Generate documentation
on:
  push:
    branches: master

jobs:
  build:
    name: Generate documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Generate documentation
        run: |
          rm docs/*.md
          go run ./tools/generate-docs

      - name: Add changes
        id: add
        uses: ./git/add

      - name: Commit changes
        if: fromJson(steps.add.outputs.staged)
        uses: ./git/commit
        with:
          title: 📄 Update generated documentation
          body: |
            This commits the output of the `generate-docs` tool.

            Source-commit: ${{ github.sha }}
            Github-workflow-id: ${{ github.run_id }}
            Github-workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Push generated changes
        if: fromJson(steps.add.outputs.staged)
        uses: ./git/push
        with:
          branch: master

