name: Promote `develop` to `master`
on:
  push:
    branches: develop

jobs:
  test:
    name: Test axios
    runs-on: ubuntu-latest
    steps:
      - name: Test axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios');

            const jiraUrl = 'YOUR_JIRA_URL';
            const apiKey = 'YOUR_API_KEY';
            const projectKey = 'PROJECT_KEY';
            const issueTypeId = '10001'; // Provide the appropriate issue type ID
            const summary = 'SUMMARY_OF_THE_ISSUE';

            const createIssue = async () => {
              try {
                const response = await axios.post(
                  `${jiraUrl}/rest/api/3/issue`,
                  {
                    fields: {
                      project: {
                        key: projectKey
                      },
                      summary,
                      issuetype: {
                        id: issueTypeId
                      }
                    }
                  },
                  {
                    headers: {
                      'Content-Type': 'application/json',
                      'Authorization': `Bearer ${apiKey}`
                    }
                  }
                );

                console.log('Issue created successfully:', response.data.key);
              } catch (error) {
                console.error('Error creating issue:', error.response.data);
              }
            };

  setup:
    name: Setup Tests
    permissions:
      contents: write
    uses: ./.github/workflows/test-prepare.yaml

  test-pull-requests:
    name: Test Pull Requests
    needs: [setup]
    permissions:
      pull-requests: write
      issues: write
      contents: write
    uses: ./.github/workflows/test-pull-request.yaml
    with:
      branch: ${{ needs.setup.outputs.branch }}
      base: ${{ needs.setup.outputs.target-branch }}

  test-issues:
    name: Test Issues
    needs: [setup]
    permissions:
      issues: write
    uses: ./.github/workflows/test-issue.yaml

  test-releases:
    name: Test Releases
    needs: [setup]
    permissions:
      contents: write
    uses: ./.github/workflows/test-release.yaml
    with:
      branch: ${{ needs.setup.outputs.branch }}

  promote:
    name: Promote to master
    needs:
      - setup
      - test-pull-requests
      - test-issues
      - test-releases
    if: success()
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/test-success.yaml
    with:
      branch: ${{ needs.setup.outputs.branch }}

  cleanup:
    name: Cleanup
    needs:
      - setup
      - test-pull-requests
      - test-issues
      - test-releases
      - promote
    if: always()
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/test-cleanup.yaml
    with:
      branch: ${{ needs.setup.outputs.branch }}
      target-branch: ${{ needs.setup.outputs.target-branch }}
      issue-number: ${{ needs.test-issues.outputs.issue-number }}
      pull-number: ${{ needs.test-pull-requests.outputs.pull-number }}
      release-id: ${{ needs.test-releases.outputs.release-id }}
      release-tag: ${{ needs.test-releases.outputs.release-tag }}
